name: Continuous Integration

on:
  push:
    branches:
      - main
      - 'feat/cicd-**'
  pull_request:

jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions code
        uses: actions/checkout@v3
      
      - name: Set up node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20
      
      - name: Configure "headless" google chrome on the runner instance
        run: |
          sudo apt-get -y install xorg xvfb gtk2-engines-pixbuf
          sudo apt-get -y install dbus-x11 xfonts-base xfonts-100dpi xfonts-75dpi xfonts-cyrillic xfonts-scalable
          Xvfb -ac :99 -screen 0 1280x1024x16 &

      - name: Install dependencies for the angular application
        run: |
          cd ui
          npm install

      - name: Run frontend tests
        run: |
          cd ui
          npm test
        env:
          DISPLAY: :99
